CREATE TABLE CustomerAddress(
CustomerAddressId INT PRIMARY KEY IDENTITY(1,1),
Street1 NVARCHAR(100) NOT NULL,
Street2 NVARCHAR(100) NOT NULL,
City NVARCHAR(100) NOT NULL,
States NVARCHAR(100) NOT NULL, 
Zip NVARCHAR(100) NOT NULL
);