insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('East', '560', 'Huntington', 'West Virginia', '25711');
insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('Center', '380', 'Vero Beach', 'Florida', '32964');
insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('Transport', '7', 'Atlanta', 'Georgia', '30306');
insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('Derek', '2216', 'Saginaw', 'Michigan', '48604');
insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('Gale', '944', 'Huntington', 'West Virginia', '25716');
insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('Burning Wood', '9656', 'Sacramento', 'California', '95838');
insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('Pawling', '61', 'New Haven', 'Connecticut', '06520');
insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('Sheridan', '848', 'Long Beach', 'California', '90840');
insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('Hanover', '54441', 'Lexington', 'Kentucky', '40546');
insert into CustomerAddress (Street1, Street2, City, States, Zip) values ('Brickson Park', '0', 'Tampa', 'Florida', '33615');
